const qwerty = {
  en: {
    Backquote: {
      key: '`',
      capsKey: '`',
      keyCode: 192,
      code: 'Backquote',
      shiftKey: '~',
    },
    Digit1: {
      capsKey: '1',
      key: '1',
      keyCode: 49,
      shiftKey: '!',
      code: 'Digit1',
    },
    Digit2: {
      key: '2',
      capsKey: '2',
      keyCode: 50,
      code: 'Digit2',
      shiftKey: '@',
    },
    Digit3: {
      key: '3',
      capsKey: '3',
      keyCode: 51,
      code: 'Digit3',
      shiftKey: '#',
    },
    Digit4: {
      key: '4',
      capsKey: '4',
      keyCode: 52,
      code: 'Digit4',
      shiftKey: '$',
    },
    Digit5: {
      key: '5',
      capsKey: '5',
      keyCode: 53,
      code: 'Digit5',
      shiftKey: '%',
    },
    Digit6: {
      key: '6',
      capsKey: '6',
      keyCode: 54,
      code: 'Digit6',
      shiftKey: '^',
    },
    Digit7: {
      key: '7',
      capsKey: '7',
      keyCode: 55,
      code: 'Digit7',
      shiftKey: '&',
    },
    Digit8: {
      key: '8',
      capsKey: '8',
      keyCode: 56,
      code: 'Digit8',
      shiftKey: '*',
    },
    Digit9: {
      key: '9',
      capsKey: '9',
      keyCode: 57,
      code: 'Digit9',
      shiftKey: '(',
    },
    Digit0: {
      key: '0',
      capsKey: '0',
      keyCode: 48,
      code: 'Digit0',
      shiftKey: ')',
    },
    Minus: {
      key: '-',
      capsKey: '-',
      keyCode: 109,
      code: 'Minus',
      shiftKey: '_',
    },
    Equal: {
      key: '=',
      capsKey: '=',
      keyCode: 61,
      code: 'Equal',
      shiftKey: '+',
    },
    Backspace: {
      key: 'Backspace',
      capsKey: 'Backspace',
      keyCode: 8,
      code: 'Backspace',
      shiftKey: 'Backspace',
    },
    Tab: {
      key: 'Tab',
      capsKey: 'Tab',
      keyCode: 9,
      code: 'Tab',
      shiftKey: 'Tab',
    },
    KeyQ: {
      key: 'q',
      keyCode: 81,
      code: 'KeyQ',
      shiftKey: 'Q',
      capsKey: 'Q',
    },
    KeyW: {
      key: 'w',
      keyCode: 87,
      code: 'KeyW',
      shiftKey: 'W',
      capsKey: 'W',
    },
    KeyE: {
      key: 'e',
      keyCode: 69,
      code: 'KeyE',
      shiftKey: 'E',
      capsKey: 'E',
    },
    KeyR: {
      key: 'r',
      keyCode: 82,
      code: 'KeyR',
      shiftKey: 'R',
      capsKey: 'R',
    },
    KeyT: {
      key: 't',
      keyCode: 84,
      code: 'KeyT',
      shiftKey: 'T',
      capsKey: 'T',
    },
    KeyY: {
      key: 'y',
      keyCode: 89,
      code: 'KeyY',
      shiftKey: 'Y',
      capsKey: 'Y',
    },
    KeyU: {
      key: 'u',
      keyCode: 85,
      code: 'KeyU',
      shiftKey: 'U',
      capsKey: 'U',
    },
    KeyI: {
      key: 'i',
      keyCode: 73,
      code: 'KeyI',
      shiftKey: 'I',
      capsKey: 'I',
    },
    KeyO: {
      key: 'o',
      keyCode: 79,
      code: 'KeyO',
      shiftKey: 'O',
      capsKey: 'O',
    },
    KeyP: {
      key: 'p',
      keyCode: 80,
      code: 'KeyP',
      shiftKey: 'P',
      capsKey: 'P',
    },
    BracketLeft: {
      key: '[',
      capsKey: '[',
      keyCode: 160,
      code: 'BracketLeft',
      shiftKey: '{',
    },
    BracketRight: {
      key: ']',
      capsKey: ']',
      keyCode: 221,
      code: 'BracketRight',
      shiftKey: '}',
    },
    Delete: {
      key: 'Delete',
      capsKey: 'Delete',
      keyCode: 46,
      code: 'Delete',
      shiftKey: 'Delete',
    },
    CapsLock: {
      key: 'CapsLock',
      capsKey: 'CapsLock',
      keyCode: 20,
      code: 'CapsLock',
      shiftKey: 'CapsLock',
    },
    KeyA: {
      key: 'a',
      keyCode: 65,
      code: 'KeyA',
      shiftKey: 'A',
      capsKey: 'A',
    },
    KeyS: {
      key: 's',
      keyCode: 83,
      code: 'KeyS',
      shiftKey: 'S',
      capsKey: 'S',
    },
    KeyD: {
      key: 'd',
      keyCode: 68,
      code: 'KeyD',
      shiftKey: 'D',
      capsKey: 'D',
    },
    KeyF: {
      key: 'f',
      keyCode: 70,
      code: 'KeyF',
      shiftKey: 'F',
      capsKey: 'F',
    },
    KeyG: {
      key: 'g',
      keyCode: 71,
      code: 'KeyG',
      shiftKey: 'G',
      capsKey: 'G',
    },
    KeyH: {
      key: 'h',
      keyCode: 72,
      code: 'KeyH',
      shiftKey: 'H',
      capsKey: 'H',
    },
    KeyJ: {
      key: 'j',
      keyCode: 74,
      code: 'KeyJ',
      shiftKey: 'J',
      capsKey: 'J',
    },
    KeyK: {
      key: 'k',
      keyCode: 75,
      code: 'KeyK',
      shiftKey: 'K',
      capsKey: 'K',
    },
    KeyL: {
      key: 'l',
      keyCode: 76,
      code: 'KeyL',
      shiftKey: 'L',
      capsKey: 'L',
    },
    Semicolon: {
      key: ';',
      capsKey: ';',
      keyCode: 59,
      code: 'Semicolon',
      shiftKey: ':',
    },
    Quote: {
      key: "'",
      capsKey: "'",
      keyCode: 222,
      code: 'Quote',
      shiftKey: '"',
    },
    Backslash: {
      key: '\\',
      capsKey: '\\',
      keyCode: 220,
      code: 'Backslash',
      shiftKey: '|',
    },
    Enter: {
      key: 'Enter',
      capsKey: 'Enter',
      keyCode: 13,
      code: 'Enter',
      shiftKey: 'Enter',
    },
    ShiftLeft: {
      key: 'Shift',
      capsKey: 'Shift',
      keyCode: 16,
      code: 'ShiftLeft',
      shiftKey: 'Shift',
    },
    KeyZ: {
      key: 'z',
      capsKey: 'Z',
      keyCode: 90,
      code: 'KeyZ',
      shiftKey: 'Z',
    },
    KeyX: {
      key: 'x',
      capsKey: 'X',
      keyCode: 88,
      code: 'KeyX',
      shiftKey: 'X',
    },
    KeyC: {
      key: 'c',
      keyCode: 67,
      code: 'KeyC',
      shiftKey: 'C',
      capsKey: 'C',
    },
    KeyV: {
      key: 'v',
      keyCode: 86,
      code: 'KeyV',
      shiftKey: 'V',
      capsKey: 'V',
    },
    KeyB: {
      key: 'b',
      keyCode: 66,
      code: 'KeyB',
      shiftKey: 'B',
      capsKey: 'B',
    },
    KeyN: {
      key: 'n',
      keyCode: 78,
      code: 'KeyN',
      shiftKey: 'N',
      capsKey: 'N',
    },
    KeyM: {
      key: 'm',
      keyCode: 77,
      code: 'KeyM',
      shiftKey: 'M',
      capsKey: 'M',
    },
    Comma: {
      key: ',',
      capsKey: ',',
      keyCode: 108,
      code: 'Comma',
      shiftKey: '<',
    },
    Period: {
      key: '.',
      capsKey: '.',
      keyCode: 190,
      code: 'Period',
      shiftKey: '>',
    },
    Slash: {
      key: '/',
      capsKey: '/',
      keyCode: 191,
      code: 'Slash',
      shiftKey: '?',
    },
    ArrowUp: {
      key: '&#9650;',
      capsKey: '&#9650;',
      keyCode: 38,
      code: 'ArrowUp',
      shiftKey: '&#9650;',
    },
    ShiftRight: {
      key: 'Shift',
      capsKey: 'Shift',
      keyCode: 16,
      code: 'ShiftRight',
      shiftKey: 'Shift',
    },
    ControlLeft: {
      key: 'Ctrl',
      capsKey: 'Ctrl',
      keyCode: 17,
      code: 'ControlLeft',
      shiftKey: 'Ctrl',
    },
    MetaLeft: {
      key: 'Win',
      capsKey: 'Win',
      keyCode: 91,
      code: 'MetaLeft',
      shiftKey: 'Win',
    },
    AltLeft: {
      key: 'Alt',
      capsKey: 'Alt',
      keyCode: 18,
      code: 'AltLeft',
      shiftKey: 'Alt',
    },
    Space: {
      key: ' ',
      capsKey: ' ',
      keyCode: 32,
      code: 'Space',
      shiftKey: ' ',
    },
    AltRight: {
      key: 'Alt',
      capsKey: 'Alt',
      keyCode: 18,
      code: 'AltRight',
      shiftKey: 'Alt',
    },
    ArrowLeft: {
      key: '&#9668;',
      capsKey: '&#9668;',
      keyCode: 37,
      code: 'ArrowLeft',
      shiftKey: '&#9668;',
    },
    ArrowDown: {
      key: '&#9660;',
      capsKey: '&#9660;',
      keyCode: 40,
      code: 'ArrowDown',
      shiftKey: '&#9660;',
    },
    ArrowRight: {
      key: '&#9658;',
      capsKey: '&#9658;',
      keyCode: 39,
      code: 'ArrowRight',
      shiftKey: '&#9658;',
    },
    ControlRight: {
      key: 'Ctrl',
      capsKey: 'Ctrl',
      keyCode: 17,
      code: 'ControlRight',
      shiftKey: 'Ctrl',
    },

  },
  ru: {
    Backquote: {
      key: 'ё',
      keyCode: 192,
      code: 'Backquote',
      shiftKey: 'Ё',
      capsKey: 'Ё',
    },
    Digit1: {
      key: '1',
      capsKey: '1',
      keyCode: 49,
      code: 'Digit1',
      shiftKey: '!',
    },
    Digit2: {
      key: '2',
      capsKey: '2',
      keyCode: 50,
      code: 'Digit2',
      shiftKey: '"',
    },
    Digit3: {
      key: '3',
      capsKey: '3',
      keyCode: 51,
      code: 'Digit3',
      shiftKey: '№',
    },
    Digit4: {
      key: '4',
      capsKey: '4',
      keyCode: 52,
      code: 'Digit4',
      shiftKey: ';',
    },
    Digit5: {
      key: '5',
      capsKey: '5',
      keyCode: 53,
      code: 'Digit5',
      shiftKey: '%',
    },
    Digit6: {
      key: '6',
      capsKey: '6',
      keyCode: 54,
      code: 'Digit6',
      shiftKey: ':',
    },
    Digit7: {
      key: '7',
      capsKey: '7',
      keyCode: 55,
      code: 'Digit7',
      shiftKey: '?',
    },
    Digit8: {
      key: '8',
      capsKey: '8',
      keyCode: 56,
      code: 'Digit8',
      shiftKey: '*',
    },
    Digit9: {
      key: '9',
      capsKey: '9',
      keyCode: 57,
      code: 'Digit9',
      shiftKey: '(',
    },
    Digit0: {
      key: '0',
      capsKey: '0',
      keyCode: 48,
      code: 'Digit0',
      shiftKey: ')',
    },
    Minus: {
      key: '-',
      capsKey: '-',
      keyCode: 109,
      code: 'Minus',
      shiftKey: '_',
    },
    Equal: {
      key: '=',
      capsKey: '=',
      keyCode: 61,
      code: 'Equal',
      shiftKey: '+',
    },
    Backspace: {
      key: 'Backspace',
      capsKey: 'Backspace',
      keyCode: 8,
      code: 'Backspace',
      shiftKey: 'Backspace',
    },
    Tab: {
      key: 'Tab',
      capsKey: 'Tab',
      keyCode: 9,
      code: 'Tab',
      shiftKey: 'Tab',
    },
    KeyQ: {
      key: 'й',
      keyCode: 81,
      code: 'KeyQ',
      shiftKey: 'Й',
      capsKey: 'Й',
    },
    KeyW: {
      key: 'ц',
      keyCode: 87,
      code: 'KeyW',
      shiftKey: 'Ц',
      capsKey: 'Ц',
    },
    KeyE: {
      key: 'у',
      keyCode: 69,
      code: 'KeyE',
      shiftKey: 'У',
      capsKey: 'У',
    },
    KeyR: {
      key: 'к',
      keyCode: 82,
      code: 'KeyR',
      shiftKey: 'К',
      capsKey: 'К',
    },
    KeyT: {
      key: 'е',
      keyCode: 84,
      code: 'KeyT',
      shiftKey: 'Е',
      capsKey: 'Е',
    },
    KeyY: {
      key: 'н',
      keyCode: 89,
      code: 'KeyY',
      shiftKey: 'Н',
      capsKey: 'Н',
    },
    KeyU: {
      key: 'г',
      keyCode: 85,
      code: 'KeyU',
      shiftKey: 'Г',
      capsKey: 'Г',
    },
    KeyI: {
      key: 'ш',
      keyCode: 73,
      code: 'KeyI',
      shiftKey: 'Ш',
      capsKey: 'Ш',
    },
    KeyO: {
      key: 'щ',
      keyCode: 79,
      code: 'KeyO',
      shiftKey: 'Щ',
      capsKey: 'Щ',
    },
    KeyP: {
      key: 'з',
      keyCode: 80,
      code: 'KeyP',
      shiftKey: 'З',
      capsKey: 'З',
    },
    BracketLeft: {
      key: 'х',
      keyCode: 160,
      code: 'BracketLeft',
      shiftKey: 'Х',
      capsKey: 'Х',
    },
    BracketRight: {
      key: 'ъ',
      keyCode: 221,
      code: 'BracketRight',
      shiftKey: 'Ъ',
      capsKey: 'Ъ',
    },
    Delete: {
      key: 'Delete',
      capsKey: 'Delete',
      keyCode: 46,
      code: 'Delete',
      shiftKey: 'Delete',
    },
    CapsLock: {
      key: 'CapsLock',
      capsKey: 'CapsLock',
      keyCode: 20,
      code: 'CapsLock',
      shiftKey: 'CapsLock',
    },
    KeyA: {
      key: 'ф',
      keyCode: 65,
      code: 'KeyA',
      shiftKey: 'Ф',
      capsKey: 'Ф',
    },
    KeyS: {
      key: 'ы',
      keyCode: 83,
      code: 'KeyS',
      shiftKey: 'Ы',
      capsKey: 'Ы',
    },
    KeyD: {
      key: 'в',
      keyCode: 68,
      code: 'KeyD',
      shiftKey: 'В',
      capsKey: 'В',
    },
    KeyF: {
      key: 'а',
      keyCode: 70,
      code: 'KeyF',
      shiftKey: 'А',
      capsKey: 'А',
    },
    KeyG: {
      key: 'п',
      keyCode: 71,
      code: 'KeyG',
      shiftKey: 'П',
      capsKey: 'П',
    },
    KeyH: {
      key: 'р',
      keyCode: 72,
      code: 'KeyH',
      shiftKey: 'Р',
      capsKey: 'Р',
    },
    KeyJ: {
      key: 'о',
      keyCode: 74,
      code: 'KeyJ',
      shiftKey: 'О',
      capsKey: 'О',
    },
    KeyK: {
      key: 'л',
      keyCode: 75,
      code: 'KeyK',
      shiftKey: 'Л',
      capsKey: 'Л',
    },
    KeyL: {
      key: 'д',
      keyCode: 76,
      code: 'KeyL',
      shiftKey: 'Д',
      capsKey: 'Д',
    },
    Semicolon: {
      key: 'ж',
      keyCode: 59,
      code: 'Semicolon',
      shiftKey: 'Ж',
      capsKey: 'Ж',
    },
    Quote: {
      key: 'э',
      keyCode: 222,
      code: 'Quote',
      shiftKey: 'Э',
      capsKey: 'Э',
    },
    Backslash: {
      key: '\\',
      capsKey: '\\',
      keyCode: 220,
      code: 'Backslash',
      shiftKey: '/',
    },
    Enter: {
      key: 'Enter',
      capsKey: 'Enter',
      keyCode: 13,
      code: 'Enter',
      shiftKey: 'Enter',
    },
    ShiftLeft: {
      key: 'Shift',
      capsKey: 'Shift',
      keyCode: 16,
      code: 'ShiftLeft',
      shiftKey: 'Shift',
    },
    KeyZ: {
      key: 'я',
      keyCode: 90,
      code: 'KeyZ',
      shiftKey: 'Я',
      capsKey: 'Я',
    },
    KeyX: {
      key: 'ч',
      keyCode: 88,
      code: 'KeyX',
      shiftKey: 'Ч',
      capsKey: 'Ч',
    },
    KeyC: {
      key: 'с',
      keyCode: 67,
      code: 'KeyC',
      shiftKey: 'С',
      capsKey: 'С',
    },
    KeyV: {
      key: 'м',
      keyCode: 86,
      code: 'KeyV',
      shiftKey: 'М',
      capsKey: 'М',
    },
    KeyB: {
      key: 'и',
      keyCode: 66,
      code: 'KeyB',
      shiftKey: 'И',
      capsKey: 'И',
    },
    KeyN: {
      key: 'т',
      keyCode: 78,
      code: 'KeyN',
      shiftKey: 'Т',
      capsKey: 'Т',
    },
    KeyM: {
      key: 'ь',
      keyCode: 77,
      code: 'KeyM',
      shiftKey: 'Ь',
      capsKey: 'Ь',
    },
    Comma: {
      key: 'б',
      keyCode: 108,
      code: 'Comma',
      location: 3,
      shiftKey: 'Б',
      capsKey: 'Б',
    },
    Period: {
      key: 'ю',
      keyCode: 190,
      code: 'Period',
      shiftKey: 'Ю',
      capsKey: 'Ю',
    },
    Slash: {
      key: '.',
      capsKey: '.',
      keyCode: 191,
      code: 'Slash',
      shiftKey: ',',
    },
    ArrowUp: {
      key: '&#9650;',
      capsKey: '&#9650;',
      keyCode: 38,
      code: 'ArrowUp',
      shiftKey: '&#9650;',
    },
    ShiftRight: {
      key: 'Shift',
      capsKey: 'Shift',
      keyCode: 16,
      code: 'ShiftRight',
      shiftKey: 'Shift',
    },
    ControlLeft: {
      key: 'Ctrl',
      capsKey: 'Ctrl',
      keyCode: 17,
      code: 'ControlLeft',
      location: 1,
      shiftKey: 'Ctrl',
    },
    MetaLeft: {
      key: 'Win',
      capsKey: 'Win',
      keyCode: 91,
      code: 'MetaLeft',
      location: 1,
      shiftKey: 'Win',
    },
    AltLeft: {
      key: 'Alt',
      capsKey: 'Alt',
      keyCode: 18,
      code: 'AltLeft',
      shiftKey: 'Alt',
    },
    Space: {
      key: ' ',
      capsKey: ' ',
      keyCode: 32,
      code: 'Space',
      shiftKey: '',
    },
    AltRight: {
      key: 'Alt',
      capsKey: 'Alt',
      keyCode: 18,
      code: 'AltRight',
      location: 1,
      shiftKey: 'Alt',

    },
    ArrowLeft: {
      key: '&#9668;',
      capsKey: '&#9668;',
      keyCode: 37,
      code: 'ArrowLeft',
      shiftKey: '&#9668;',
    },
    ArrowDown: {
      key: '&#9660;',
      capsKey: '&#9660;',
      keyCode: 40,
      code: 'ArrowDown',
      shiftKey: '&#9660;',
    },
    ArrowRight: {
      key: '&#9658;',
      capsKey: '&#9658;',
      keyCode: 39,
      code: 'ArrowRight',
      shiftKey: '&#9658;',
    },
    ControlRight: {
      key: 'Ctrl',
      capsKey: 'Ctrl',
      keyCode: 17,
      code: 'ControlRight',
      shiftKey: 'Ctrl',
    },
  },
};
export default qwerty;
